using IELTop_Content_Server.Data;
using IELTop_Content_Server.Models;
using IELTop_Content_Server.Options;
using IELTop_Content_Server.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace IELTop_Content_Server;

/// <summary>
/// Creates the store on first run, seeds the admin, the default
/// settings, and the shipped sample content. Everything here is safe to
/// run on every start.
/// </summary>
public sealed class DbInitializer(
    IDbContextFactory<AppDbContext> dbFactory,
    IAdminAuthService admins,
    IPaperService papers,
    IAudioService audio,
    IContentCache cache,
    IS3StorageService s3,
    IOptions<ServerOptions> serverOptions,
    IOptions<StorageOptions> storageOptions,
    ILogger<DbInitializer> logger)
{
    private readonly ServerOptions _server = serverOptions.Value;
    private readonly StorageOptions _storage = storageOptions.Value;

    public async Task RunAsync(CancellationToken ct = default)
    {
        await using (var db = await dbFactory.CreateDbContextAsync(ct))
        {
            await db.Database.EnsureCreatedAsync(ct);
            try
            {
                if (db.Database.IsNpgsql())
                {
                    await db.Database.ExecuteSqlRawAsync(
                        "CREATE TABLE IF NOT EXISTS \"BlockedIps\" (" +
                        "\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "\"Ip\" character varying(64) NOT NULL, " +
                        "\"Reason\" character varying(256) NOT NULL DEFAULT '', " +
                        "\"BlockedAt\" bigint NOT NULL, " +
                        "\"ExpiresAt\" bigint, " +
                        "\"CreatedBy\" character varying(64) NOT NULL DEFAULT 'System'" +
                        ");" +
                        "CREATE INDEX IF NOT EXISTS \"IX_BlockedIps_Ip\" ON \"BlockedIps\" (\"Ip\");", ct);

                    await db.Database.ExecuteSqlRawAsync(
                        "ALTER TABLE \"Papers\" ADD COLUMN IF NOT EXISTS \"IsExclusive\" boolean NOT NULL DEFAULT false;" +
                        "ALTER TABLE \"Papers\" ADD COLUMN IF NOT EXISTS \"ExclusiveCode\" character varying(128) NOT NULL DEFAULT '';" +
                        "ALTER TABLE \"Catalog\" ADD COLUMN IF NOT EXISTS \"IsExclusive\" boolean NOT NULL DEFAULT false;" +
                        "ALTER TABLE \"Catalog\" ADD COLUMN IF NOT EXISTS \"ExclusiveCode\" character varying(128) NOT NULL DEFAULT '';" +
                        "ALTER TABLE \"Audio\" ADD COLUMN IF NOT EXISTS \"Format\" character varying(16) NOT NULL DEFAULT 'm4a';" +
                        "ALTER TABLE \"Audio\" ADD COLUMN IF NOT EXISTS \"IsStandardized\" boolean NOT NULL DEFAULT true;" +
                        "ALTER TABLE \"Audio\" ADD COLUMN IF NOT EXISTS \"S3Url\" character varying(512) NOT NULL DEFAULT '';", ct);
                }
                else
                {
                    await db.Database.ExecuteSqlRawAsync(
                        "CREATE TABLE IF NOT EXISTS \"BlockedIps\" (" +
                        "\"Id\" INTEGER PRIMARY KEY AUTOINCREMENT, " +
                        "\"Ip\" TEXT NOT NULL, " +
                        "\"Reason\" TEXT, " +
                        "\"BlockedAt\" INTEGER NOT NULL, " +
                        "\"ExpiresAt\" INTEGER, " +
                        "\"CreatedBy\" TEXT" +
                        ");" +
                        "CREATE INDEX IF NOT EXISTS \"IX_BlockedIps_Ip\" ON \"BlockedIps\" (\"Ip\");", ct);

                    try { await db.Database.ExecuteSqlRawAsync("ALTER TABLE Papers ADD COLUMN IsExclusive INTEGER NOT NULL DEFAULT 0;", ct); } catch { }
                    try { await db.Database.ExecuteSqlRawAsync("ALTER TABLE Papers ADD COLUMN ExclusiveCode TEXT NOT NULL DEFAULT '';", ct); } catch { }
                    try { await db.Database.ExecuteSqlRawAsync("ALTER TABLE Catalog ADD COLUMN IsExclusive INTEGER NOT NULL DEFAULT 0;", ct); } catch { }
                    try { await db.Database.ExecuteSqlRawAsync("ALTER TABLE Catalog ADD COLUMN ExclusiveCode TEXT NOT NULL DEFAULT '';", ct); } catch { }
                    try { await db.Database.ExecuteSqlRawAsync("ALTER TABLE Audio ADD COLUMN Format TEXT NOT NULL DEFAULT 'm4a';", ct); } catch { }
                    try { await db.Database.ExecuteSqlRawAsync("ALTER TABLE Audio ADD COLUMN IsStandardized INTEGER NOT NULL DEFAULT 1;", ct); } catch { }
                    try { await db.Database.ExecuteSqlRawAsync("ALTER TABLE Audio ADD COLUMN S3Url TEXT NOT NULL DEFAULT '';", ct); } catch { }
                }
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Failed to ensure BlockedIps table exists");
            }
        }

        if (s3.Enabled)
        {
            await s3.EnsureBucketCreatedAsync(ct);
        }

        await admins.EnsureSeedAsync(ct);
        await SeedSettingsAsync(ct);
        await SeedContentAsync(ct);

        if (s3.Enabled)
        {
            await SyncContentToS3Async(ct);
        }
    }

    private async Task SeedSettingsAsync(CancellationToken ct)
    {
        var defaults = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["server.name"] = _server.Name,
            ["server.skills"] = System.Text.Json.JsonSerializer.Serialize(
                _server.Skills.Count > 0 ? _server.Skills : ServerOptions.DefaultSkills),
            ["auth.anonymous"] = _server.AllowAnonymous.ToString(),
            ["auth.code"] = _server.AllowAccessCode.ToString(),
            ["auth.login"] = _server.AllowLogin.ToString(),
            ["content.version"] = "1",
            ["setup.completed"] = "true"
        };

        await using var db = await dbFactory.CreateDbContextAsync(ct);
        var existing = await db.Settings.Select(s => s.Key).ToListAsync(ct);
        var missing = defaults.Where(kv => !existing.Contains(kv.Key, StringComparer.OrdinalIgnoreCase)).ToList();
        if (missing.Count == 0)
            return;

        foreach (var (key, value) in missing)
            db.Settings.Add(new Setting { Key = key, Value = value });
        await db.SaveChangesAsync(ct);
    }

    private async Task SeedContentAsync(CancellationToken ct)
    {
        int paperCount = await papers.CountAsync(ct);
        if (paperCount == 0 && !string.IsNullOrWhiteSpace(_storage.SeedFolder))
        {
            string folder = StoragePaths.Resolve(_storage.SeedFolder);
            if (Directory.Exists(folder))
            {
                int imported = await papers.ImportFolderAsync(folder, overwrite: true, ct);
                logger.LogInformation("Seeded {Count} papers from {Folder}", imported, folder);
            }
            else
            {
                logger.LogInformation("Seed folder {Folder} does not exist, skipping.", folder);
            }
        }

        var names = await audio.NamesAsync(ct);
        if (names.Count == 0 && !string.IsNullOrWhiteSpace(_storage.SeedFolder))
        {
            string folder = StoragePaths.Resolve(_storage.SeedFolder);
            if (Directory.Exists(folder))
                await audio.ImportFolderAsync(folder, overwrite: false, ct);
        }

        await cache.BumpVersionAsync(ct);
    }

    private async Task SyncContentToS3Async(CancellationToken ct)
    {
        try
        {
            // Sync audio files to S3 if not already in S3
            string audioRoot = audio.Root;
            if (Directory.Exists(audioRoot))
            {
                foreach (var file in Directory.EnumerateFiles(audioRoot))
                {
                    ct.ThrowIfCancellationRequested();
                    string fileName = Path.GetFileName(file);
                    string key = $"audio/{fileName}";
                    if (!await s3.ExistsAsync(key, ct))
                    {
                        await using var stream = File.OpenRead(file);
                        await s3.UploadAsync(key, stream, audio.ContentTypeFor(fileName), ct);
                        logger.LogInformation("Synced audio {File} to S3", fileName);
                    }
                }
            }

            // Sync papers JSON to S3 as backups
            await using var db = await dbFactory.CreateDbContextAsync(ct);
            var papersList = await db.Papers.AsNoTracking().Select(p => new { p.Id, p.Json }).ToListAsync(ct);
            foreach (var p in papersList)
            {
                ct.ThrowIfCancellationRequested();
                string key = $"papers/{p.Id}.json";
                if (!await s3.ExistsAsync(key, ct))
                {
                    using var stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(p.Json));
                    await s3.UploadAsync(key, stream, "application/json", ct);
                    logger.LogInformation("Synced paper {Id} to S3", p.Id);
                }
            }
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Failed to complete S3 content sync.");
        }
    }
}
